language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
services:
- mongodb
before_install:
- npm install -g grunt
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: Unsg1BN+GSDiwTqURjDfq9fC5meqhefBo3q0Kmy8hwPAMaGBdM08XL9dJleH6xxDLIro+xJv8dRinrTcoIFrshXs8rA+OPs4zlw1xSzxrCcEbAfxD6jCq66mI1nKcz5e4qrJo2nXUue6SjL9GHre3AKZcvNxJNy0BJ7yFhLnYq01+c67Y9fqM/ljyZP8VYMcU4u6CUTDWXXfhntaZfk1fI16cFw59AN6R68DbBFql668R0Uv4DgHfVlIXYyBEiSyR82bddUg2/z4KVebyQx7B2Ml92ZvvEn5Jj2rDjqQDsrZGQahUJ8OESJuVLky0kNbMtjWDGXcRTDo6SjRUJQHusvTjYsqLvlpVmpkr4hQI3nCXbk6ywa9cUFG/b3hUfaE/CLIAxhsbi+S8lPC4xt4ZXtjbsn+hfLOeEEhzGaBQxgRBCFMRMgacsrdUyiEzAbq8hie0IUzKguA41aDMurFk1abUa1Lv/1cPLX7LP24PGtXSmVBpKe48oTXPofZwNXE6lhAefZf9TnZkK/3jOrXmUV9VpeK8P9CISRAiROBxHf7MnQ1jWVfBb2gjOnsikRwEvi9Cg/StISYd3japKI9sccO1YVSmUotZ9Lii8mSDqUOWIWhdKuRXaWk+OyPqh7CGPh/W5oc+UDwUhGxv7OdbOxbetAvfY0P1ZdfEiS8/yQ=
  app: floating-basin-53892
after_deploy:
