language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
services:
- mongodb
before_install:
- npm install -g grunt
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: cGC4wbvXTpqPx5PS/RXZeoJa5b0Y0CpH/nTj4kFhVIh8QMtSoa6E2XzJyCDjoYhBwkRnEsrkVtoIPbVxugk6iKYjpSANGIYADVgpU+W9qjqz26dY35rsKa89ufbIQ+J1zSY87rE1UYZthI9vuIvq3M9LR8C5mM2KjDw0jx1JnY0vwYhdVZ107ea6RN/F/omPHnpkYpzIEVDxC2/Ns61HchjpjgmJE3tgxmt3ZOwYX24H5TuD+on0KmiL/5B6yZhThsQMfL1cChr8G+oO19vGfdiO00rU2sed0NzTqo9HjOFjCjNmlzEEA2dCaFBHyxPS4OKbdKVPHVj66b+bl7TkJ+wpJDRaVyMpF9GxNBs6GDapGkYBDaokOWDrSeewxqX6Rh/Nso7jjoBN9ou3MjVAJVSCHruI8BVtTrxdrG0rNCqjfwG24/hx2FsJYsnZC+50gY8pbB7L3C6Y+tZVTR9JEOku8cwM6rbQU5yWPArXbc1cOrM3smV4hIJhr0v4dqe+rAGrGjHTU5DSDK9mh/g7qXaH63lgFSkEUQJAdDVGmMQq7yWRdQsNOogwZBWoCDugBZroRr8nc2HVsgKc6GKKtm4cxBr7Rnso20gD3Hc5KugLWr7kdACuOHiIP3PornLvnhZ0AN9LEYlx6imH52J76cxi7qbuf82wWH1SyWdqwa0=
  app: floating-basin-53892
after_deploy:
