language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
env:
  global:
    secure: pKjNy/kB41O9SzGfDreVGxm+9+qeHOABHtGaxBl0Meh1QhY9PqsxzPlb1eDwHo6ZBCKM4/jnFi3qMgdm/VTLGWfmFxZ1eQVItSFCSd9bV6d9OUY5oeBKIzmM7mllrYC4BOAaqndMuGJmI9Wbi07Jpe1bsjhXr7lkslR3IY0dkPtT5YduH9B0MuUGyYwE5QsumgPKnAGnC552FdCQUAvk2Ai8fb2lR65KExzAvXAqZFnM+AtQuIq/SyAmwlBv9THHxCcGqhsgdZV1uRfg4h1KX2dl8oaqgz7tTLXMlxufYij2auAZV2aOGWKc5yOOPlYewiWAsWIT9fC6PLH2NFM9wn7aeB0ndisLxhAQQjkKqfP5NkHRuc3c4eyM0oDtsuvtXzzC1s0R/M4Tlm2Fm4YZdYni7To/fEAnkPqMpWcXUCzflQfVGoL8VX1UqySSrHvaDmeEtzRAYulpNH7i3tk0ddAlKMW9IKicVRCXC8Gtb7S4Nj9XCNWXKpUzRhvKOelLVcubvD7OJmsBJxrsjN8F/7Wfe+i5OWaTbCn04c+SkmhjJl5+CQEe2Yu8aaYLeSc3S+K2f18Bnum1VhHrkbaDXTeRM/A26r29STkkdUIqJkH3uBqehfTLDa+jz+8zxQ5jyZv82kpeCamLh65rKkrEB0S2HxOdFC3zj3l0f0YDTSI= #FUi9jZdap1ySS/4dDbcGy65Xmk4hgqwiSslskyHF5cgUVahVXuLV/pFz2XtBx4MN+NU/X4oG3JcbMNrj77XakmVlGIMucpeJCgKlKPki8B/FjbA5tI8hU+7bXjcXhHCD/hjy28Fd87YiBA5RpAugf63qYVwKTrTnT01Gp2+3ffkT+V5CS68STFBhB3wpwa3Ez9iK5w/tgyieqGvkmjjEskKXaba+8BD3R5dg4WhPuOmL6f41WXGCFVtn9iYhGxBp2ZZrd2Iy6Zwz8SNmZEl6+ZHCdI+nEFSr1nJ9oYlusaHuqkKcWYxN0aKEXTkq/tjVfeWztLdStPKMO+ECPpJ1PPBv24+XJyadwFJKh7l1/opfjGk6PKDiPb1sGij3ZOwY3Jg1LPS8AkujsW5kI8+q0krMMCaIgAZuioGSth9FZSITrZDj37a6D7tda8bq4TohSuWMo8nbeeKLGdIJ6A5xHNnJlC6P8B4h+C3qcsik5I9N8H0CYdRlPDBUxAn4WtdPXKRxn8fnvtcTFyrdu6X7rTSnlDQn+dPigkHmE0UzcDrpW8YZ5zBePgsx1FF+qlfF3wT07qunkLvIW3mq1cCvDg4riRq8sxEbv1TKAWNAPbeLp+vSgde4M0MNX3ZgTXqhWZi89wHQ+fcJCJF6FxA7s1H0wjqvuo7QYTmZRRIjrLg=
services:
- mongodb
before_install:
- npm install -g grunt
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: dxwwbCr0Rt1vcmp7ND/wCj5Y9n7WXiztNnNbXzGJU9+w96R8usz4gWrKdDRkwswRDj2qmhQsISyl3vmqYjGFEFhW+Gu6jej+BnTVaBV3Jz69pRgwiZgPHqHaTxRzeYOCy+IyiFCflVeV93a7QDdyVTb1IHiouCSHMYSNXSA9XCwQ99UKIDVXLXNu1x8wFuU350dYp/TPKQ3TFLACEjDA1bsomLZ8T5ue2V6zKq3TmcNp2CHncRI1yZJdNEjjWcwYO/fDKjqbYy8j0HDAjjXhvCYNUjC5tHGG71Eo7eRgfXEzcbfmJYEENs9nbErUdvKRkS4l6l/2afv3OS9mD7sRGcmY+ErQ+5SB5clTM6ZdFi8a/BECQ3W5QYTYhmYA7T7aTGrgyBQbapzld5IEi8YtAXYlSOYTS2M0+oOts9nDm+smEo3v6HGQkSW00c/w1K01wOYFKkRAHtkIu8CLjOKsyvwdcIIqx+bqdDTOBEOMD4GFf4m1nLWnAkMWGQRmIRBcxJ9iFX/timj8YKApv/ZayLw4+UjrHo4VLWEUKB0U+YEkoU2NTM3hkFkT0O+IXiEZ70SsSCU/maj6s58mpxMcqJtidp35rb283R8BC8gH/jWDitS3tBJe1S+RhclyHziWNXZWpKl+8yDOu3f+UHGjUmPRVEc8KB6fnfMwOdifqbs=
  app: floating-basin-53892
after_deploy:
