language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
services:
- mongodb
before_install:
- npm install -g grunt
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: GjuA9HAVOO5bxDqh7xjhQEk7xjOBUCZjjnP0c9oCyE99gBgAQxPgt7YBbObk/jihUNO5ZjpNJupYJGsKbv0caBUqyjfjKNe1GCxEjLSET39kQ10MHday5knzzCwk//Feyswyr4R4gYNjVCYZsnJdbgLQHoBUxJvbowCdxeVSvA1kURGmKL4xHZkH6KRMfdAbgDsVFJqoe7ojRssBd8HFE84Hm+1ysO36l78C8RrEwvZz4TtT0mwqcOtrMZiDj4l7JorH8gi5RxJrteLloOPrTrgSd0U/L6XZFVV+ipBEj1t9zUGy3McdKp4dow2ZUci0G8rm24oVEXtIbE/SsWgZqFuJybSBs3+tgKc/FlLrwA4/qV5WwCcLqmYoPqVObh4LrQfaXaMWafgovGJakLlRqnyjk+cnHjLpFn5PQhVcgw3grROjywiXj7TDQiUYt4xj8wkJcKYNsSjAmRCY+3o79J/0mf4RpLwxkzJYL7JYqj5UnJcVSsOkyeoHKrg7fjvzWsxpNmU4Hq81f/QwbTOvoxAc7JzrtVvdGhFSSlUxpWAHIwFlpU3gCiVYOoWyIHCo0IfmMRjqbIWTslF/PlPixm/dm4Ze+CMSy49H0aVX+sTVcwVHvQ1FCwuGQh+Xc4pzBfoOluQ/fFBCkX7bMsty6MiRc9fGB25cIOo0u+h+mZA=
  app: floating-basin-53892
after_deploy:
