language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
services:
- mongodb
before_install:
- npm install -g grunt
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: fOLs3QzHHoFbF37J5O+b5y/l/UkioW94bbiBwofWOV1SJzA29mub8bByBC26oVx1djRB6ytHN5rY8Pe8TuS9mhN2T1O1FtmHJx6+dp/Tp2Ho7y9CFpMXZGaesIWZ8ZF7fnLVAYY48bdwcfPg0xYIJmeaI0wHJm/Sblz7V8uNR2NpdmN24vSmF6mGxx0yptTeWCAo83w1kKGkURgkL2lXzM37ti0MGZUPKm9ph5IO5n8XfgMRzMB+VLpvFqPzmfDv0XzWQf5//m+XidozLmp6nfe4eYpS/hvQDdw2gUyIpyrew5maNPxLam5MEAJQwGIoFkThX0QTbOwLFFbrhsGZVZwvUCg3GKRrygpBCOfgrUHguGk5Q9CSsLsUz5A+HnBfRLLk4diMmGf7C3y9l+Dh18P6vUKktWtTHFnSP21nCfAf9Vhkgwty4KjalaswyxeoVMfV/9fUpof0YF74scyE5dqLsaIcwYIJ8W6766C/EzQkDf0DHE2V9YSTord8pj4pwqjvoy8l7gVdCjDTImX6FbT45eyDrmhjtMcGW5NZH/Dnl28g9rEscRkwEVkvrSAzc0JYHvslz5u6SPUoWMekvyxUNoJThWajtBRGdeOvzzRAAbfq9BYalSPlH1P7laGnQhReVCgdYykklBeq6Jhgo7Xck9ARixgW2YEBf9hOToQ=
  app: floating-basin-53892
after_deploy:
