language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
services:
- mongodb
before_install:
- npm install -g grunt
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: dxwwbCr0Rt1vcmp7ND/wCj5Y9n7WXiztNnNbXzGJU9+w96R8usz4gWrKdDRkwswRDj2qmhQsISyl3vmqYjGFEFhW+Gu6jej+BnTVaBV3Jz69pRgwiZgPHqHaTxRzeYOCy+IyiFCflVeV93a7QDdyVTb1IHiouCSHMYSNXSA9XCwQ99UKIDVXLXNu1x8wFuU350dYp/TPKQ3TFLACEjDA1bsomLZ8T5ue2V6zKq3TmcNp2CHncRI1yZJdNEjjWcwYO/fDKjqbYy8j0HDAjjXhvCYNUjC5tHGG71Eo7eRgfXEzcbfmJYEENs9nbErUdvKRkS4l6l/2afv3OS9mD7sRGcmY+ErQ+5SB5clTM6ZdFi8a/BECQ3W5QYTYhmYA7T7aTGrgyBQbapzld5IEi8YtAXYlSOYTS2M0+oOts9nDm+smEo3v6HGQkSW00c/w1K01wOYFKkRAHtkIu8CLjOKsyvwdcIIqx+bqdDTOBEOMD4GFf4m1nLWnAkMWGQRmIRBcxJ9iFX/timj8YKApv/ZayLw4+UjrHo4VLWEUKB0U+YEkoU2NTM3hkFkT0O+IXiEZ70SsSCU/maj6s58mpxMcqJtidp35rb283R8BC8gH/jWDitS3tBJe1S+RhclyHziWNXZWpKl+8yDOu3f+UHGjUmPRVEc8KB6fnfMwOdifqbs=
  app: floating-basin-53892
after_deploy:
